# Generated by Django 3.1.7 on 2021-08-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='course-images/')),
                ('category', models.CharField(choices=[('Video', 'Video'), ('Blog', 'Blog')], max_length=10)),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='course-images/')),
                ('summary', models.TextField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Project',
            },
        ),
    ]
