# Generated by Django 3.1.7 on 2021-08-12 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.CharField(default=datetime.datetime.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.CharField(default=datetime.datetime(2021, 8, 12, 8, 13, 20, 93517), max_length=200),
            preserve_default=False,
        ),
    ]
