# Generated by Django 3.1.7 on 2021-10-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210812_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('demo_url', models.CharField(max_length=200)),
            ],
        ),
    ]
